//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhioImporter.Districts {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siliconholler.net/geopolitical", ConfigurationName="Districts.IVotingDistricts")]
    public interface IVotingDistricts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVotingDistricts/getTypes", ReplyAction="http://siliconholler.net/geopolitical/IVotingDistricts/getTypesResponse")]
        VoterWatch.dataclasses.districttype[] getTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVotingDistricts/searchDistricts", ReplyAction="http://siliconholler.net/geopolitical/IVotingDistricts/searchDistrictsResponse")]
        VoterWatch.dataclasses.districtsearch searchDistricts(string typeid, string ident, string name, string descr, string skip, string take, int sseq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVotingDistricts/getDistricts", ReplyAction="http://siliconholler.net/geopolitical/IVotingDistricts/getDistrictsResponse")]
        VoterWatch.dataclasses.district[] getDistricts(int typeid, string skip, string take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVotingDistricts/getAllDistricts", ReplyAction="http://siliconholler.net/geopolitical/IVotingDistricts/getAllDistrictsResponse")]
        VoterWatch.dataclasses.district[] getAllDistricts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVotingDistricts/getParents", ReplyAction="http://siliconholler.net/geopolitical/IVotingDistricts/getParentsResponse")]
        VoterWatch.dataclasses.district[] getParents(int childid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVotingDistricts/getChildren", ReplyAction="http://siliconholler.net/geopolitical/IVotingDistricts/getChildrenResponse")]
        VoterWatch.dataclasses.district[] getChildren(int parentid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVotingDistrictsChannel : OhioImporter.Districts.IVotingDistricts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VotingDistrictsClient : System.ServiceModel.ClientBase<OhioImporter.Districts.IVotingDistricts>, OhioImporter.Districts.IVotingDistricts {
        
        public VotingDistrictsClient() {
        }
        
        public VotingDistrictsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VotingDistrictsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VotingDistrictsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VotingDistrictsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoterWatch.dataclasses.districttype[] getTypes() {
            return base.Channel.getTypes();
        }
        
        public VoterWatch.dataclasses.districtsearch searchDistricts(string typeid, string ident, string name, string descr, string skip, string take, int sseq) {
            return base.Channel.searchDistricts(typeid, ident, name, descr, skip, take, sseq);
        }
        
        public VoterWatch.dataclasses.district[] getDistricts(int typeid, string skip, string take) {
            return base.Channel.getDistricts(typeid, skip, take);
        }
        
        public VoterWatch.dataclasses.district[] getAllDistricts() {
            return base.Channel.getAllDistricts();
        }
        
        public VoterWatch.dataclasses.district[] getParents(int childid) {
            return base.Channel.getParents(childid);
        }
        
        public VoterWatch.dataclasses.district[] getChildren(int parentid) {
            return base.Channel.getChildren(parentid);
        }
    }
}
