//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhioImporter.Structure {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siliconholler.net/geopolitical", ConfigurationName="Structure.IDistrictModel")]
    public interface IDistrictModel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IDistrictModel/addType", ReplyAction="http://siliconholler.net/geopolitical/IDistrictModel/addTypeResponse")]
        VoterWatch.dataclasses.districttype addType(VoterWatch.dataclasses.districttype ntype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IDistrictModel/updateType", ReplyAction="http://siliconholler.net/geopolitical/IDistrictModel/updateTypeResponse")]
        VoterWatch.dataclasses.districttype updateType(VoterWatch.dataclasses.districttype udata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IDistrictModel/addDistrict", ReplyAction="http://siliconholler.net/geopolitical/IDistrictModel/addDistrictResponse")]
        VoterWatch.dataclasses.district addDistrict(VoterWatch.dataclasses.district ndistrict);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IDistrictModel/updateDistrict", ReplyAction="http://siliconholler.net/geopolitical/IDistrictModel/updateDistrictResponse")]
        VoterWatch.dataclasses.district updateDistrict(VoterWatch.dataclasses.district udata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IDistrictModel/deleteDistrict", ReplyAction="http://siliconholler.net/geopolitical/IDistrictModel/deleteDistrictResponse")]
        bool deleteDistrict(VoterWatch.dataclasses.district deldata);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IDistrictModel/addParent", ReplyAction="http://siliconholler.net/geopolitical/IDistrictModel/addParentResponse")]
        bool addParent(VoterWatch.dataclasses.districtrelationship addrel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IDistrictModel/removeParent", ReplyAction="http://siliconholler.net/geopolitical/IDistrictModel/removeParentResponse")]
        bool removeParent(VoterWatch.dataclasses.districtrelationship remrel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IDistrictModel/removeParents", ReplyAction="http://siliconholler.net/geopolitical/IDistrictModel/removeParentsResponse")]
        bool removeParents(int childid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IDistrictModel/removeChildren", ReplyAction="http://siliconholler.net/geopolitical/IDistrictModel/removeChildrenResponse")]
        bool removeChildren(int parentid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDistrictModelChannel : OhioImporter.Structure.IDistrictModel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistrictModelClient : System.ServiceModel.ClientBase<OhioImporter.Structure.IDistrictModel>, OhioImporter.Structure.IDistrictModel {
        
        public DistrictModelClient() {
        }
        
        public DistrictModelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistrictModelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistrictModelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistrictModelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoterWatch.dataclasses.districttype addType(VoterWatch.dataclasses.districttype ntype) {
            return base.Channel.addType(ntype);
        }
        
        public VoterWatch.dataclasses.districttype updateType(VoterWatch.dataclasses.districttype udata) {
            return base.Channel.updateType(udata);
        }
        
        public VoterWatch.dataclasses.district addDistrict(VoterWatch.dataclasses.district ndistrict) {
            return base.Channel.addDistrict(ndistrict);
        }
        
        public VoterWatch.dataclasses.district updateDistrict(VoterWatch.dataclasses.district udata) {
            return base.Channel.updateDistrict(udata);
        }
        
        public bool deleteDistrict(VoterWatch.dataclasses.district deldata) {
            return base.Channel.deleteDistrict(deldata);
        }
        
        public bool addParent(VoterWatch.dataclasses.districtrelationship addrel) {
            return base.Channel.addParent(addrel);
        }
        
        public bool removeParent(VoterWatch.dataclasses.districtrelationship remrel) {
            return base.Channel.removeParent(remrel);
        }
        
        public bool removeParents(int childid) {
            return base.Channel.removeParents(childid);
        }
        
        public bool removeChildren(int parentid) {
            return base.Channel.removeChildren(parentid);
        }
    }
}
