//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhioImporter.VoterInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siliconholler.net/geopolitical", ConfigurationName="VoterInfo.IVoterInfo")]
    public interface IVoterInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVoterInfo/searchVoters", ReplyAction="http://siliconholler.net/geopolitical/IVoterInfo/searchVotersResponse")]
        VoterWatch.dataclasses.votersearch searchVoters(string stateid, string countyid, string districtid, string lastname, string firstname, string middlename, string suffix, string yob, string skip, string take, int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVoterInfo/searchAddresses", ReplyAction="http://siliconholler.net/geopolitical/IVoterInfo/searchAddressesResponse")]
        VoterWatch.dataclasses.addresssearch searchAddresses(string addrid, string addr1, string addr2, string city, string state, string zip, string z4, string skip, string take, int seq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVoterInfo/getVoter", ReplyAction="http://siliconholler.net/geopolitical/IVoterInfo/getVoterResponse")]
        VoterWatch.dataclasses.voter getVoter(int vid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVoterInfo/getAddresses", ReplyAction="http://siliconholler.net/geopolitical/IVoterInfo/getAddressesResponse")]
        VoterWatch.dataclasses.address[] getAddresses(int vid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVoterInfo/getPollDistrict", ReplyAction="http://siliconholler.net/geopolitical/IVoterInfo/getPollDistrictResponse")]
        VoterWatch.dataclasses.district getPollDistrict(int vid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVoterInfo/getVotingDistricts", ReplyAction="http://siliconholler.net/geopolitical/IVoterInfo/getVotingDistrictsResponse")]
        VoterWatch.dataclasses.district[] getVotingDistricts(int vid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVoterInfo/getAddressVoters", ReplyAction="http://siliconholler.net/geopolitical/IVoterInfo/getAddressVotersResponse")]
        VoterWatch.dataclasses.votersearch getAddressVoters(int addrid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVoterInfo/getDistrictVoters", ReplyAction="http://siliconholler.net/geopolitical/IVoterInfo/getDistrictVotersResponse")]
        VoterWatch.dataclasses.voter[] getDistrictVoters(int districtid, string affid, string skip, string take);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://siliconholler.net/geopolitical/IVoterInfo/getParties", ReplyAction="http://siliconholler.net/geopolitical/IVoterInfo/getPartiesResponse")]
        VoterWatch.dataclasses.affiliation[] getParties();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoterInfoChannel : OhioImporter.VoterInfo.IVoterInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoterInfoClient : System.ServiceModel.ClientBase<OhioImporter.VoterInfo.IVoterInfo>, OhioImporter.VoterInfo.IVoterInfo {
        
        public VoterInfoClient() {
        }
        
        public VoterInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoterInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoterInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoterInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoterWatch.dataclasses.votersearch searchVoters(string stateid, string countyid, string districtid, string lastname, string firstname, string middlename, string suffix, string yob, string skip, string take, int seq) {
            return base.Channel.searchVoters(stateid, countyid, districtid, lastname, firstname, middlename, suffix, yob, skip, take, seq);
        }
        
        public VoterWatch.dataclasses.addresssearch searchAddresses(string addrid, string addr1, string addr2, string city, string state, string zip, string z4, string skip, string take, int seq) {
            return base.Channel.searchAddresses(addrid, addr1, addr2, city, state, zip, z4, skip, take, seq);
        }
        
        public VoterWatch.dataclasses.voter getVoter(int vid) {
            return base.Channel.getVoter(vid);
        }
        
        public VoterWatch.dataclasses.address[] getAddresses(int vid) {
            return base.Channel.getAddresses(vid);
        }
        
        public VoterWatch.dataclasses.district getPollDistrict(int vid) {
            return base.Channel.getPollDistrict(vid);
        }
        
        public VoterWatch.dataclasses.district[] getVotingDistricts(int vid) {
            return base.Channel.getVotingDistricts(vid);
        }
        
        public VoterWatch.dataclasses.votersearch getAddressVoters(int addrid) {
            return base.Channel.getAddressVoters(addrid);
        }
        
        public VoterWatch.dataclasses.voter[] getDistrictVoters(int districtid, string affid, string skip, string take) {
            return base.Channel.getDistrictVoters(districtid, affid, skip, take);
        }
        
        public VoterWatch.dataclasses.affiliation[] getParties() {
            return base.Channel.getParties();
        }
    }
}
